### PR TITLE
Fixed a bug that broke the reconnect loop and changed the disconnect callback

### PR DESCRIPTION
**Pull request by klaashoekstra94**
Too bad, I just noticed I pushed my previous PR too quickly, so I missed a bug.
@winterscar Could you maybe also merge this PR to fix it?

Edit: I also moved the call to the disconnect callback to after the first retry when auto reconnect is enabled, since I saw that the connection is reset every now and then.

### CODE REVIEW

**Comment by winterscar** [comment]
@klaashoekstra94, you seem to be making a few commits here, will you let me know when you’d like me to merge?

thanks.

**Comment by klaashoekstra94** [comment]
@winterscar Yeah sorry, I found a couple of more bugs during testing, but I think it's all working now.
If you want or have the time, it'd be great if you could test it as well.

**Comment by klaashoekstra94** [comment]
> @klaashoekstra94, you seem to be making a few commits here, will you let me know when you’d like me to merge?
@winterscar It would be great if you can merge the PR.

**Comment by klaashoekstra94** [comment]
@winterscar bump :)

**Pull request merged**
